In [5]:
# 기본 구조 선언 (2.39)
import torch
from torch import nn
from torch import optim
from torch.utils.data import TensorDataset, DataLoader 


train_x = torch.FloatTensor([    
    [1, 2], [2, 3], [3, 4], [4, 5], [5, 6], [6, 7]
])
train_y = torch.FloatTensor([
    [0.1, 1.5], [1, 2.8], [1.9, 4.1], [2.8, 5.4], [3.7, 6.7], [4.6, 8]
])

In [3]:
# 데이터 세트와 데이터 로더 (3.30)
train_dataset = TensorDataset(train_x, train_y)
train_dataloader = DataLoader(train_dataset, batch_size=2, shuffle=True, drop_last=True)

In [4]:
# 모델, 오차함수, 최적화 함수 (3.31)
model = nn.Linear(2, 2, bias=True) #선형회귀 - 입출력 데이터 차원의 크기
criterion = nn.MSELoss()
optimizer = optim.SGD(model.parameters(), lr=0.001)

In [6]:
# 데이터 로더 적용 (3.32)
for epoch in range(20000):
    cost = 0.0
    
    for batch in train_dataloader:
        x, y = batch
        output = model(x)
        loss = criterion(output, y)
        
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
        
        cost += loss

    cost = cost / len(train_dataloader)
    
    if (epoch + 1) % 1000 == 0:
        print(f"Epoch : {epoch+1:4d}, Model : {list(model.parameters())}, Cost : {cost:.3f}")

Epoch : 1000, Model : [Parameter containing:
tensor([[ 0.9386, -0.0954],
        [ 0.6408,  0.5787]], requires_grad=True), Parameter containing:
tensor([-0.4655, -0.0401], requires_grad=True)], Cost : 0.017
Epoch : 2000, Model : [Parameter containing:
tensor([[ 0.9963, -0.1252],
        [ 0.7225,  0.5366]], requires_grad=True), Parameter containing:
tensor([-0.5530, -0.1640], requires_grad=True)], Cost : 0.004
Epoch : 3000, Model : [Parameter containing:
tensor([[ 1.0257, -0.1404],
        [ 0.7641,  0.5150]], requires_grad=True), Parameter containing:
tensor([-0.5975, -0.2271], requires_grad=True)], Cost : 0.001
Epoch : 4000, Model : [Parameter containing:
tensor([[ 1.0406, -0.1481],
        [ 0.7853,  0.5041]], requires_grad=True), Parameter containing:
tensor([-0.6202, -0.2593], requires_grad=True)], Cost : 0.000
Epoch : 5000, Model : [Parameter containing:
tensor([[ 1.0482, -0.1521],
        [ 0.7961,  0.4985]], requires_grad=True), Parameter containing:
tensor([-0.6318, -0.2757], 