### [10. 퍼셉트론]

- 퍼셉트론(Perceptron)   
퍼셉트론이란, 인공신경망의 한 종류로서 출력이 0 또는 1인 작업을 의미하는 이진 분류에 해당하는 간단한 모델이다. 퍼셉트론은 신경세포가 신호를 전달하는 구조와 유사한 방식으로 구현됐다.    
퍼셉트론은 TLU(Threshold Logic Unit) 형태를 기반으로 하며, 계단함수를 적용해 결과를 반환한다. 즉 퍼셉트론의 입력값과 노드의 가중치를 곱한 값을 모두 더했을 때 임곗값보다 크면1을 출력하고 작으면 0을 출력한다.

In [1]:
import torch
import pandas as pd
from torch import nn
from torch import optim
from torch.utils.data import Dataset, DataLoader


class CustomDataset(Dataset):
    def __init__(self, file_path):
        df = pd.read_csv(file_path)
        self.x1 = df.iloc[:, 0].values
        self.x2 = df.iloc[:, 1].values
        self.y = df.iloc[:, 2].values
        self.length = len(df)

    def __getitem__(self, index):
        x = torch.FloatTensor([self.x1[index], self.x2[index]])
        y = torch.FloatTensor([self.y[index]])
        return x, y

    def __len__(self):
        return self.length

class CustomModel(nn.Module):
    def __init__(self):
        super().__init__()

        self.layer = nn.Sequential(
            nn.Linear(2, 1),
            nn.Sigmoid()
        )

    def forward(self, x):
        x = self.layer(x)
        return x

In [131]:
train_dataset = CustomDataset("../datasets/data.csv")
train_dataloader = DataLoader(train_dataset, batch_size=10, shuffle=True, drop_last=True)

device = "cuda" if torch.cuda.is_available() else "cpu"
model = CustomModel().to(device)
criterion = nn.BCELoss().to(device)
optimizer = optim.SGD(model.parameters(), lr=0.01)

In [132]:
# Check the length of the dataset
print(f"Length of dataset: {len(train_dataset)}")

# Check the length of the dataloader
print(f"Length of dataloader: {len(train_dataloader)}")

# Make sure the dataloader has data
if len(train_dataloader) == 0:
    raise ValueError("Dataloader is empty. Please check your dataset and dataloader configuration.")

for epoch in range(10000):
    cost = 0.0

    for x, y in train_dataloader:
        x = x.to(device)
        y = y.to(device)

        output = model(x)
        loss = criterion(output, y)

        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        cost += loss

    cost = cost / len(train_dataloader)

    if (epoch + 1) % 1000 == 0:
        print(f"Epoch : {epoch+1:4d}, Cost : {cost:.3f}")

with torch.no_grad():
    model.eval()
    inputs = torch.FloatTensor([
        [0, 0],
        [0, 1],
        [1, 0],
        [1, 1]
    ]).to(device)
    outputs = model(inputs)
    
    print("---------")
    print(outputs)
    print(outputs <= 0.5)


Length of dataset: 47
Length of dataloader: 4


C:\Users\SDLPC187\AppData\Local\Temp\ipykernel_18376\999614697.py:17: DeprecationWarning: In future, it will be an error for 'np.bool_' scalars to be interpreted as an index
  x = torch.FloatTensor([self.x1[index], self.x2[index]])
C:\Users\SDLPC187\AppData\Local\Temp\ipykernel_18376\999614697.py:18: DeprecationWarning: In future, it will be an error for 'np.bool_' scalars to be interpreted as an index
  y = torch.FloatTensor([self.y[index]])


Epoch : 1000, Cost : 0.628
Epoch : 2000, Cost : 0.624
Epoch : 3000, Cost : 0.626
Epoch : 4000, Cost : 0.629
Epoch : 5000, Cost : 0.593
Epoch : 6000, Cost : 0.658
Epoch : 7000, Cost : 0.624
Epoch : 8000, Cost : 0.623
Epoch : 9000, Cost : 0.656
Epoch : 10000, Cost : 0.657
---------
tensor([[0.3328],
        [0.1634],
        [0.6427],
        [0.4133]], device='cuda:0')
tensor([[ True],
        [ True],
        [False],
        [ True]], device='cuda:0')


In [136]:
import torch
import pandas as pd
from torch import nn
from torch import optim
from torch.utils.data import Dataset, DataLoader


class CustomDataset(Dataset):
    def __init__(self, file_path):
        df = pd.read_csv(file_path)
        self.x1 = df.iloc[:, 0].values
        self.x2 = df.iloc[:, 1].values
        self.y = df.iloc[:, 2].values
        self.length = len(df)

    def __getitem__(self, index):
        x = torch.FloatTensor([self.x1[index], self.x2[index]])
        y = torch.FloatTensor([self.y[index]])
        return x, y

    def __len__(self):
        return self.length


class CustomModel(nn.Module):
    def __init__(self):
        super(CustomModel, self).__init__()

        self.layer1 = nn.Sequential(
            nn.Linear(2, 2),
            nn.Sigmoid()
        )
        self.layer2 = nn.Sequential(
            nn.Linear(2, 1),
            nn.Sigmoid()
        )

    def forward(self, x):
        x = self.layer1(x)
        x = self.layer2(x)
        return x


train_dataset = CustomDataset("../datasets/data.csv")
train_dataloader = DataLoader(train_dataset, batch_size=10, shuffle=True, drop_last=True)

device = "cuda" if torch.cuda.is_available() else "cpu"
model = CustomModel().to(device)
criterion = nn.BCELoss().to(device)
optimizer = optim.SGD(model.parameters(), lr=0.01)

for epoch in range(10000):
    cost = 0.0

    for x, y in train_dataloader:
        x = x.to(device)
        y = y.to(device)

        output = model(x)
        loss = criterion(output, y)

        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        cost += loss

    cost = cost / len(train_dataloader)

    if (epoch + 1) % 1000 == 0:
        print(f"Epoch : {epoch+1:4d}, Cost : {cost:.3f}")


with torch.no_grad():
    model.eval()
    inputs = torch.FloatTensor([
        [0, 0],
        [0, 1],
        [1, 0],
        [1, 1]
    ]).to(device)
    outputs = model(inputs)
    
    print('---------')
    print(outputs)
    print(outputs <= 0.5)

C:\Users\SDLPC187\AppData\Local\Temp\ipykernel_18376\1674957799.py:17: DeprecationWarning: In future, it will be an error for 'np.bool_' scalars to be interpreted as an index
  x = torch.FloatTensor([self.x1[index], self.x2[index]])
C:\Users\SDLPC187\AppData\Local\Temp\ipykernel_18376\1674957799.py:18: DeprecationWarning: In future, it will be an error for 'np.bool_' scalars to be interpreted as an index
  y = torch.FloatTensor([self.y[index]])


Epoch : 1000, Cost : 0.696
Epoch : 2000, Cost : 0.676
Epoch : 3000, Cost : 0.675
Epoch : 4000, Cost : 0.639
Epoch : 5000, Cost : 0.554
Epoch : 6000, Cost : 0.450
Epoch : 7000, Cost : 0.347
Epoch : 8000, Cost : 0.329
Epoch : 9000, Cost : 0.288
Epoch : 10000, Cost : 0.303
---------
tensor([[0.0447],
        [0.3018],
        [0.9555],
        [0.3440]], device='cuda:0')
tensor([[ True],
        [ True],
        [False],
        [ True]], device='cuda:0')
